src/components/IconModal.vue
Resolves https://github.com/uiowa/brand-icon-browser/issues/11
How to test
1. Check out `main`
2. Open a modal
3. Note the warnings that appear in the browser development console when clicking an icon in the list
4. check out fix-undefined-currentVariant branch
5. Open a modal
6. No more warnings? Fixed.
=> removed unused properties from modal download buttons

src/App.vue, src/components/IconModal.vue
This was leftover from when SearchBar.vue was included in each view separately instead of App.vue, removed extra searchTerm prop from IconModal
Resolves https://github.com/uiowa/brand-icon-browser/issues/13
How to test
- Check out main
- Open the webapp
- Note the warnings that appear in the browser development console when clicking an icon in the list
- check out `fix-extraneous-non-emits-on-load`
- refresh/reload web app
- No more warnings? Fixed.
=> removed setCurrentSearch term prop from router-view

src/components/Icon.vue, src/components/IconList.vue
After refactoring some of the code that fetches different variants and formats of images, the `IconList` component was pulling in PNG files, but I prefer rendering SVGs in the IconList component.
=> Load SVG files in main icon list, fixes a regression that was forcing PNGs to render in the list.

package-lock.json, package.json
This should resolve https://github.com/uiowa/brand-icon-browser/issues/29 as well as provide the correct color profile for the icons.
=> Updated uiowa-brand-icons package

src/components/IconList.vue, src/composables/getIconSrc.js
SVGs were looking "jaggedy" / had bad aliasing on lower DPI screens:
This switches us back to presenting PNGs instead.
=> Clean up getIconSrc composable, switch back icon list to use PNGs

src/App.vue, src/components/IconModal.vue
Resolves #36
This PR makes the following adjustments to the Icon modal preview:
- Icon modal is now much more mobile friendly (screenshot below)
- Mobile: Icon modal is scrollable if content overflows vertically
- Mobile: Button groups are now just buttons
- Escape key closes modal when open
- `<body>` element is no longer scrollable when modal is open
=> Icon preview modal adjustments

src/App.vue, src/components/SearchBar.vue, src/components/Settings.vue
Resolves #35 
Before:
After:
Still not perfect, but not completely broken
=> search bar mobile style touchups and fixes #35

src/components/IconModal.vue
This PR fixes a CSS class rename from `.active` to `.icon-preview--active` that was incomplete. I forgot to add the appropriate markup to the template.
=> Fixed icon preview active class that was in <style> but not used properly in markup

src/App.vue
Resolves #44 
At some point I removed this prop that's passed via the `<router-view>` element.
How to test:
1. Click any icon in any view (category/home/doesn't matter)
2. Click on a tag ("#academics" for example)
3. Note that "academics" (or whichever tag you clicked) is in the search bar as expected.
=> Ensure that @setCurrentSearchTerm is defined as a prop on router-view in order for search terms to be linked to the input field within the view

src/App.vue, src/components/IconList.vue, src/components/IconModal.vue
After starting on work implementing the UIDS button component, I'm realizing that the inconsistency of the border radius isn't really desirable despite my earlier reservations.
This PR gives the icon buttons (and related borders, e.g., the icon modal previews) a border radius of 1px. colored with `#ccc` in order to more closely match the UIDS cards. 
The following screenshots include changes from the [`uids_buttons` branch](https://github.com/uiowa/brand-icon-browser/tree/uids-buttons) in order to demonstrate how the borders look more consistent, however the buttons aren't fully implemented in this branch yet.
=> Cardlike borders across the board

public/404.html
This prevents some strange redirects. I forgot to set this properly after changing deployment target from `uiowa.github.io/brand-icon-browser` to `icons.brand.uiowa.edu`.
=> ensure that 404.html's pathSegmentsToKeep variable is set properly

src/components/IconModal.vue
As mentioned by @joewhitsitt in https://github.com/uiowa/brand-icon-browser/issues/2#issuecomment-1164597652, for consistency's sake, this PR moves the "X" (close button) to the top-right instead of the top-left.
=> Move close button to the right in IconModal

src/views/CategoryView.vue
Resolves #54
Previously we were erroneously looping through and filtering icons that had a partial match in the icon name instead of an exact match and were displaying icons like `hospital-bill-payment` and `hospital-bill-checklist` when we only wanted to see `hospital`.
This PR changes the filter to an exact match. Thanks again @sondracue! 
- Check out this branch
- Click the "Campus Buildings" category
- Note that `hospital-bill`, `hospital-bill-checklist`, `hospital-bill-payment`, `hospital-bill-question` are now gone from the icon list.
=> Ensure we're looking for an exact match in the icon name in a category instead of a 'includes'-type check

src/components/CategoryListItem.vue, src/components/Icon.vue, src/components/IconList.vue, src/components/IconModal.vue
Partially resolves https://github.com/uiowa/brand-icon-browser/issues/14
This PR gives the `<Icon>` element's rendered `<img>` element explicit `height` and `width` attributes in order to help prevent reflows/jittering in some cases (e.g. when opening an `<IconModal>` component).
=> Set icon image height and width to be explicit to help with reflows/jitters

src/components/IconModal.vue
Previously, GA4 events were not being tracked for individual icon downloads due to GA4 not counting image files as `file_download` events.
VueJS can't do `@click` events easily on anchor tags (preventDefault is required in order to add functions to anchor tags and breaks the links), so this PR adds containers around each download button and tracks `@click` events on the containers instead of on the anchor itself.
=> Added container divs around download buttons for event tracking

src/components/IconModal.vue
This follows GA4's naming scheme of not naming things in the past tense. 
Renames `icon_downloaded` to `icon_download`
=> Renamed icon_download event name to match file_download

src/App.vue
Resolves #72 
This PR provides the default copyright footer text (including a dynamic `currentYear` variable) below the download, submit feedback, and privacy notice links. It also adjusts the separator color to match the border of the new `uids-button` component and adjusts the spacing between the download button and the links below it.
Preview:
1. `npm run serve`
2. Observe the links in the sidebar
3. (optional) Leave browser window open for an entire year, refresh and see the copyright year update.
=> Add copyright notice

.github/workflows/gh-pages.yml
Resolves #77 
This PR clears out the `js/` and `css/` folders during the Main branch preparations to prevent excess `app.[hash].js` and `app.[hash].css` file creations leftover from previous builds.
This change to a GitHub Actions Workflow has been tested in a forked repo:
Forked repo:
https://github.com/quamsta/brand-icon-browser
Forked `gh-pages.yml`:
https://github.com/quamsta/brand-icon-browser/blob/main/.github/workflows/gh-pages.yml
This repo has a `gh-pages` branch just like the original where its `js/` and `css/` folders have been cleared of all previous versions upon running the modified`.github/workflows/gh-pages.yml` Workflow by making an arbitrary change to `App.vue`:
https://github.com/quamsta/brand-icon-browser/tree/gh-pages/js …
=> Remove js/ and css/ folders during main branch preparations task

src/views/CategoryView.vue, src/views/HomeView.vue, src/views/SearchView.vue
Resolves #79 
`HomeView` 
1. Load the live version of the site in a browser: https://icons.brand.uiowa.edu
2. Note that `torii-gate` appears near beginning of the list (after `art-building-west`)
3. Pull down this branch, run `npm serve` to open the site locally and note that it now appears correctly sorted further down the list.
`SearchView`
1. Load the live version of the site in a browser: https://icons.brand.uiowa.edu
2. Search for "architecture" in the search bar
3. Note that `torii-gate` appears near beginning of the list (after `art-building-west`)
4. Pull down this branch, run `npm serve` to open the site locally 
5. Search for "architecture" in the search bar and note that it now appears correctly sorted in the list.
`CategoryView`
I don't have a good test case for the sidebar …
=> Alphabetically sort icons in all views

src/components/IconModal.vue
This differentiates a manually typed search from a click on a tag (e.g. "#diversity") in an `IconModal`
=> Added specific tag clicking event instead of just a search

src/components/IconModal.vue
As per Sondra's request, the button labels have been swapped as follows:
Before:
After
:
=> Swapped format and variant labels on download buttons

package-lock.json, package.json
Updates the brand icons to the latest version, directly related to this PR:
https://github.com/uiowa/brand-icons/pull/17
> 
> Fixed some misspelled icon names in categories.json that hadn't been updated when icons.json was corrected.
> 
> Also, based on some analytics data, I fixed the following empty/no results errors by tagging some icons with these tags:
> 
> access
> address
> alum
> alumni
> appointment
> athletics
> audience
> author
> class
> contact
> creative
> decision
> electric
> leader
> major
> meet
> meeting
> promote
> protect
> sanitation
> shot
> smile
> story
> success
> sustainability
> target
> vaccination
> visit
> web
> website
> writer
=> Updated uiowa-brand-icons dependency

package-lock.json, package.json
Added a few tags to childrens-hospital for easier searching: 
https://github.com/uiowa/brand-icons/commit/b761a236a423e7a297bfd5b83fe37b5a7e07913f
=> Updated brand-icons dependency Added a few tags to childrens-hospital for easier searching

package-lock.json, package.json
Directly tied to: https://github.com/uiowa/brand-icons/commit/f63f6b8cc5316e5c9715105e19293d86b578be82
Adds "engineering" and "engineer" to some icons (no icons were showing up under "engineering" before):
=> Updated brand-icons dependency

package-lock.json, package.json
Directly tied to https://github.com/uiowa/brand-icons/commit/429185510a6371d7b49f073d5874777e473e09bc
Adds some results for the terms: history, parent, peer, punctuation
=> Updated brand icons dependency

package-lock.json, package.json
Directly tied to https://github.com/uiowa/brand-icons/commits/main
Adds icons to the following search terms based on the Data Studio Report for empty search terms:
- approve
- approved
- change
- circle
- correlation
- crisis
- improvement
- kinnick stadium
- librarian
- light bulb
- market
- morning
- process
- risk
- speak
- stadium
- sunset
- thunder
Adjusted results for
- graph
=> updated icons dependency

package-lock.json, package.json
I forgot to commit the latest dependency update in the last PR (https://github.com/uiowa/brand-icon-browser/pull/98) -- that PR only contained a couple of the items in the full PR. 
This should be the correct PR for these items:
> This updates the uiowa-brand-icons dependency to the latest version and includes search results for the following terms:
> 
> achieve
> achievement
> analytics
> belonging
> biopsy
> communicate
> destination
> faculty
> funding
> infect
> infection
> progress
=> updated icon dependency again

package-lock.json, package.json
This update to the node packages resolves: https://github.com/uiowa/brand-icons/issues/21
1. Visit the live Icon Browser site: https://icons.brand.uiowa.edu
2. Search for `chromosome` in the search bar and note that there's an icon named `chromosome` that's actually a set of books and an icon named `chromosome_1` that is the actual chromosome icon.
3. Check out this branch: `chromosome-books-fix` and run `npm install` to get the latest packages
4. Run `npm run build`(may take a while, but required since icons need to be regenerated to accurately test)
5. Run `npm run serve`
6. Visit `http://localhost:8080`
7. Search for `chromosome` and note that the `chromosome` icon now appears correctly
8. Search for `books` and note that the `books` icon now appears alongside other, similar …
=> Updated uiowa-brand-icons and other node packages
